// user
export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_REGISTER = "FETCH_USER_REGISTER";
export const FETCH_USER_LOGIN = "FETCH_USER_LOGIN";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
export const STORE_TOKEN = "STORE_TOKEN";
export const DELETE_TOKEN = "DELETE_TOKEN";
export const ON_CHANGE_USER = "ON_CHANGE_USER";
export const RESET_USER_STATE = "RESET_USER_STATE";

// cars
export const FETCH_CARS_START = "FETCH_CARS_START";
export const FETCH_CARS_SUCCESS = "FETCH_CARS_SUCCESS";
export const FETCH_CARS_ERROR = "FETCH_CARS_ERROR";
export const FETCH_CARS_POST = "FETCH_CARS_POST";
export const FETCH_CARS_DELETE = "FETCH_CARS_DELETE";
export const ON_CHANGE_CARS = "ON_CHANGE_CARS";
export const RESET_CAR_STATE = "RESET_CAR_STATE";
